### ISSUE TITLE
numeric input doesnt accept float numbers

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#141]
The numeric input is not working with float numbers. 

Please check discussion https://github.com/mljar/mercury/issues/121#issuecomment-1183309838

**Comment by connorferster** [comment]
Hi @pplonski!

I took a look at the `Numeric.tsx` widget to see if I could make a contribution to this (even though I do not know TypeScript...).

Without knowing much about how React and `setWidgetValue` works, I am wondering if it makes sense to perform the input validations in the function body instead of returning code that performs the validations in the browser. It seems that the assumption is that `value` and `min` and `max` are all numbers but they may not be numbers when entering `-` or `.`

Anyway, just some thoughts. I am hoping that the numeric widget can be updated soon as I will be starting my course next week (we had to increase enrollment maximum, twice!). I am very excited to teach Mercury to the structural engineers in my course.

Thanks again!

**Comment by connorferster** [comment]
Thanks for the suggestion, @pplonski. I just tried removing my `max` and re-starting mercury but the behavior is still there.

I was planning on using Heroku, too!

That is disappointing. I might have to use their paid option for use in the course over a short period of time. One dyno can support multiple mercury apps so I think I will probably still use Heroku to "showcase" everyone's mercury apps.

**Comment by pplonski** [comment]
I will look into it!

**Comment by pplonski** [comment]
Hi @connorferster, 

I've removed the `react-numeric-input` package and use instead simple HTML `input` with `number` type. I hope it will work as expected now :)

**Comment by pplonski** [comment]
It is fixed in Mercury V2. A new release should be available in a moment.
