### ISSUE TITLE
Unable to open uploaded image file in "widgets" using Pillow

### ISSUE THREAD

**Issue by pythonista-blitz** [mljar/mercury#236]
Hi, @pplonski . How can I open an image uploaded in the "widgets" file using Pillow? The following code doesn't work:

```python
import mercury as mr
from PIL import Image
file = mr.File(label="Upload the file", max_file_size="100MB")
filepath = file.filepath
im = Image.open(filepath)
```

Thank you for always responding quickly. Please take a break once in a while.

**Comment by pplonski** [comment]
Hi @pythonista-blitz,

Apologize for problem. It was a bug in widgets code. I've already fixed it and released a new version `2.1.8`.

Here is an example code for loading and displaying image. Please note that I'm using `IPython.display.display` function to show image in the notebook. You can display image in the notebook by simply leaving `im` variable at the end of the code cell, but it will not work with `if` statement and I want to make sure that file was uploaded. That's why `display()` function.

```python
import mercury as mr
from PIL import Image
from IPython.display import display

# upload widget
file = mr.File(label="Upload the file", max_file_size="100MB")

# load and display image
if file.filepath is not None:
    im = Image.open(file.filepath)
    display(im)

```

Thank you for your help and patience!
