### ISSUE TITLE
Green Run Button No Longer Re-Executes Entire Notebook

### ISSUE THREAD

**Issue by NSC9** [mljar/mercury#264]
I tried updating my web app https://huggingface.co/spaces/NSC9/Artificial_Calculus_Teacher and I have encountered a lot of errIors.

I now see the green run button, but it does not rerun the whole notebook. I need the whole notebook refreshed completely each time in order to generate new mathematical expressions.

Work around until this is figured out is to simply tell my users to refresh the web application when they are ready to generate a new problem to solve. I removed the green run button and side bar entirely.

The problem with this workaround is when I go to [nsc9.github.io](nsc9.github.io) on my iphone, the LaTeX displays improperly and is unreadable. It works fine on a laptop. I used to have users fix broken LaTeX by refreshing the page but now that option is occupied since the run button does not work like it did 6 months ago.

**Comment by pplonski** [comment]
Hi @NSC9,

Thanks for reporting the issue. The version V2 of Mercury is completely different than V1 - that's why confusion, sorry!

We changed the name of the package. It is not `mercury` instead of `mljar-mercury`.

The green run button is hidden by default. The notebook is automatically updated after any widget update. You can update notebook after run button pressed by setting `continuous_update=False` when creating `App` object.

From your links I see that you solved all issues :)

@NSC9 if you have more questions please reopen this issue. I'm happy to help! 

What do you think about V2 of Mercury?

**Comment by NSC9** [comment]
> Hi @NSC9,
> 
> Thanks for reporting the issue. The version V2 of Mercury is completely different than V1 - that's why confusion, sorry!
> 
> We changed the name of the package. It is not `mercury` instead of `mljar-mercury`.
> 
> The green run button is hidden by default. The notebook is automatically updated after any widget update. You can update notebook after run button pressed by setting `continuous_update=False` when creating `App` object.
> 
> From your links I see that you solved all issues :)
> 
> @NSC9 if you have more questions please reopen this issue. I'm happy to help!
> 
> What do you think about V2 of Mercury?

I like that V2 Mercury has the settings integrated directly in the notebook rather than the previous clunky HTML tag at the top of the notebook.

I am reopening this issue because when I open the sidebar and click run, nothing happens. Previously, when I pressed run, the whole notebook would re-execute and new mathematical equations would be generated.

Also, did you mean "It is `mercury` instead of `mljar-mercury`"? At the moment I have it set to `mercury>=2.2.6`.

**Comment by pplonski** [comment]
Hi @NSC9,

Thank you for response. Apologize for confusion. The process of moving from YAML config to Python API is not finished in 100%. There are still some examples with old `mercury` version. I will update the embedding example website because it has old version of `mercury` (https://github.com/mljar/runmercury-website/issues/3).

The new `mercury` version is available under `mercury` package - the way you are using it is correct.

The `Run` button triggers the re-execution only of cell that are below updated widget. In your case, there are no widgets - that's why there is no re-execution.

Maybe the better solution might be to use a [`Button`](https://runmercury.com/docs/input-widgets/button/) to generate new equations. I've set `continuous_update=True` and re-execute cells below button. Below is a simple demo: 
![Peek 2023-05-23 11-49](https://github.com/mljar/mercury/assets/6959032/f7a2df3f-a81d-4aff-aeb3-15e49373d50c)

Link to the app:
https://pplonski-artificial-calculus-teacher-d0540fc.hf.space/app/calculus

Link to the code:
https://huggingface.co/spaces/pplonski/Artificial_Calculus_Teacher/blob/main/calculus.ipynb

I've added a `Button` and when it is clicked all cells below the widget are re-executed. Please notice that you need to use `.clicked` property of the button after it is clicked. It resets the information about click (so you can click button again ...).

Please create a new ticket for problems with LaTeX on mobile.

Thank you for your help and feedback.
