### ISSUE TITLE
Don't run the book at all until "Run" is pressed

### ISSUE THREAD

**Issue by kapily** [mljar/mercury#281]
Hi - is there a way you can prevent running the notebook until the green "Run" button is pressed? 

The use case is that the notebook runs some expensive queries and we don't want to do that until the user has filled out the parameters and hits the Run button.

I've already set `continuous_update=False`, but that doesn't stop the initial run of the notebook.

There are hacky work-arounds, like maybe calling Stop() if the input is empty, but would be nice if this was supported out of the box. And possibly for this use case, the `app` declaration can be on the first line.

**Comment by pplonski** [comment]
Hi @kapily,

Thank you for reporting the issue. I can add `initial_run=False` argument in the `App` class, but it can be a little tricky (dangerous for developers). Mercury is rendering widgets if there are widgets in the cell output. If I disable initial run of the notebook, then it should be developer responsibility to have some widgets in the cell's output (because `mercury` will not run all cells on start). For example, if you call `mercury run` on the notebook with no outputs the you will not see any widgets in the sidebar.

The alternative solution might be to run expensive query on button click. If data is loaded then proceed with computations, otherwise call `Stop()`. Here is an example https://runmercury.com/examples/load-on-click/ 

I don't think that second solution is hacky or ugly. I'm afraid that the first solution might rise many concerns for developers. What are your thoughts?

**Comment by kapily** [comment]
Ahh makes sense, I think you're right. The approach I suggested seems more hacky than the way things currently work (which are logical from a procedural approach). feel free to close this thread out!
